---
title: "Fasta files"
output: html_document
date: "2023-07-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(tidyverse)
library(seqinr)

setwd("E:/Cours/SupAgro/Stage M1/Analyses/Romann/Data")

#importation of the taxa table
tax_final2<-readRDS("tax_2207final.rds")
tax_euka<-readRDS("tax_euka2207final2.rds")

```

```{r table}
taxtax<-merge(tax_final2[1], tax_final2[2],by=0)
taxeuka<-merge(tax_euka[1], tax_euka[2], by=0)
```

```{r function}

create.fasta <- function(x){  #x is the specific genus we want
  
  #finding the sequences of that genus x 
  seqs<-c() #will contain sequences
  names<-c() #will contain their names
  count<-0 #will contain the nb of sequences found
  for (i in 1:12963){
    if (is.na(taxtax[i,7])==FALSE & taxtax[i,7]==x){ #if belongs to genus
      seqs<-c(seqs,taxtax[i,1]) #add seq to list
      count<-count+1
      sp<-NA 
      if (is.na(taxtax[i,8])==FALSE & taxtax[i,15]>50){ #if there is an identified species with satisfactory bootstrap value
        sp<-taxtax[i,8] #keep that species name
      }
      names<-c(names,paste0(x,"__",sp,count)) #the name of the seq will be genus name, a unique nb, potential species name
    }
  }
  result<-cbind(seqs,names)
  return(result)
}


create.fasta.euka <- function(rank, x){  #rank is the level of classification we want as the nb of column, x is the specific taxon we want in this level
  
  #finding the sequences of that taxon x 
  seqs<-c() #will contain sequences
  names<-c() #will contain their names
  count<-0 #will contain the nb of sequences found
  for (i in 1:12963){
    if (is.na(taxeuka[i,rank])==FALSE & taxeuka[i,rank]==x){ #if belongs to taxon x
      seqs<-c(seqs,taxeuka[i,1]) #add seq to list
      count<-count+1
      sp<-NA #more precise taxon
      if (is.na(taxeuka[i,rank+1])==FALSE & taxeuka[i,rank+1+7]>50){ #if there is an identified lower taxon with satisfactory bootstrap value
        sp<-taxeuka[i,rank+1] #keep that taxon name
      }
      names<-c(names,paste0(x,"__",sp,count)) #the name of the seq will be genus name, a unique nb, potential species name
    }
  }
  result<-cbind(seqs,names)
  return(result)
}

```

```{r creating fasta}

#using fungi table
result<-create.fasta("g__Pyrenophora")

seqs = as.list(result[,1])
names = as.list(result[,2])
write.fasta(seqs, names, "Pyrenophora.fasta",
            open = "w", as.string = FALSE)


```

```{r creating fasta euka}
#using euka table
result<-create.fasta.euka(7, "g__Triticum")

seqs = as.list(result[,1])
names = as.list(result[,2])
write.fasta(seqs, names, "Triticum.fasta",
            open = "w", as.string = FALSE)
```

