############## PROB INSECTS X READS


```{r echo=FALSE}
setwd("E:/Cours/SupAgro/Stage M1/Analyses/Maya/codes")
library(data.table)
library(dplyr)
library(ggplot2)

rm(list=ls()) #to clear the memory if needed

```

***packages***

# DATA 

bug<-read.table("newbug.txt",header=T)

options("digits"=5, "scipen"=0)  #notation - 5 digits, not scientific,

##### merge rows/data treatment #####

aggbug<-aggregate(cbind(p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p1, p20, p21, p22, p23,
                        p24, p25, p26, p27, p28, p29, p2, p30, p31, p32, p33, p34, p35, p36, p37,
                        p38, p39, p3, p40, p41, p42, p43, p44, p45, p46, p47, p48, p49, p4, p50, p51,
                        p52, p53, p54, p55, p56, p57, p58, p59, p5, p60, p61, p62, p63, p64, p65, p66,
                        p67, p68, p69, p6, p70, p71, p72, p73, p74, p75, p76, p77, p78, p79, p7, p80,
                        p81, p82, p83, p84, p85, p86, p87,p88, p89, p8, p90, p91, p92, p9) ~ spp + Guild, data = bug, sum)
#to merge the same insects together

guilds<-aggbug[,2]
aggbug2<-aggbug[,-2] #to remove the guilds

rownames(aggbug2)<-aggbug2[,1] #first column is species names, we want them as titles
aggbug3<-aggbug2[,-1] #delete first column with names
aggbug4<-aggbug3[,-79:-87]#delete (part of) samples with entire insects
readsbug<-aggbug4[,-80:-82]#delete (rest of) samples with entire insects (2 parts separated because the 8th sample was in between)

###CREATING TABLE WITH BINARY VALUES (PRESENT/MISSING)
binbug<-(readsbug) #second table created based on reads one
binbug[binbug>0]<-1 #if 1 read or more, take value 1 (presence) (else, still 0, absence)

#we want the values need to be read as numbers, not text
binbug[] <- lapply(binbug, as.numeric)
readsbug[] <- lapply(readsbug, as.numeric)


#we create a new variable which is the sum of reads for each insect
sum_bugbin <- rowSums(binbug) 
sum_bugreads <- rowSums(readsbug) 

#we add them to the table
newbin <- cbind(binbug, sum_col = sum_bugbin)
newreads <- cbind(readsbug, sum_col = sum_bugreads)

#sum of reads for each sample
sum_samplereads <- colSums(newreads)
#add to table
newreads2 <- rbind(newreads, sum_row = sum_samplereads)

####NOW for each insect we want the proba to find it in a sample
bugprob<-newbin$sum_col/80
finalbin <- cbind(newbin, real_detection_prob = bugprob)

#proportion reads
totreads<-sum(sum_bugreads) ####HERE IS THE TOTAL OF READS, CHANGE IT TO AAAALL INSECTS READS NOT ONLY IDENTIFIED ONES 
readsprop<-newreads2$sum_col/totreads
finalreads<-cbind(newreads2, reads_proportion = readsprop)


##### THEORETICAL RESULTS

modelprob<-finalreads  #same structure as the observed table
### On s'intéresse à l'issue "oui ou non un read de cet insecte" pour chaque échantillon donc binomiale??

###### BINOMIAL FOR THE WHOLE TABLE 
for (i in 1:40) {
  for (j in 1:80) {
    prob0=dbinom(x=0,   #First w want the proba to have 0 reads of the insect in the whole sample
           size=finalreads[41,j],        # Number of trials (n > = 0) so number of reads for the sample j
           prob=finalreads[i,82],        # The probability of success on each trial
           log = FALSE) # If TRUE, probabilities are given as log
    modelprob[i,j]<-1-prob0  #finally we want P(>=1) = 1-(P(X=0))
  }
  print (paste(rownames(modelprob)[i], modelprob[i])) #to check if everything goes well
}

# MEAN PROB FOR EACH INSECT
modelmean<-rowMeans(modelprob[,1:80]) 
modelprob[,81]<-modelmean
modelprob[41,81]<-rowSums(modelprob[41,1:80]) #we want the sum for this last line

##Result table to make it clearer
result1<-modelprob[-41,]
result2<- cbind (result1, finalbin$real_detection_prob)
result3<-result2[,-1:-80]

#just so that it looks better
colnames(result3)[1] <- "theor_detection_prob"  
colnames(result3)[3] <- "real_detection_prob"
results<-result3[c("theor_detection_prob", "real_detection_prob", "reads_proportion")]

### Difference to the model value

diff <- results$theor_detection_prob - results$real_detection_prob
resultbias <- cbind (results, diff)

### mean of reads
readscol<-finalreads[1:40,81]
readsmean<- readscol/finalbin$sum_col   ###mean for AT LEAST ONE READ
resultbias2<-cbind(resultbias, readsmean)


############################### KHI SQUARE DISTANCE

#######Now we want values for the model (not only proba) 
#update, looks like for the sum it's exactly the same as the finalreads... but it can be useful if change in numb tot of reads?
modelnum<-modelprob

for (i in 1:40) {
  for (j in 1:80) {
    modelnum[i,j]<- modelnum[i,82]*modelnum[41,j]
  }
  modelnum[i,81]<-rowSums(modelnum[i,1:80])
}

####khi dist
khidist<-c()
for (i in 1:40) {
  khidist<-c(khidist,(finalreads[i,81] - modelnum[i,81])**2/modelnum[i,81])
}
khidist

resultbias3<-cbind(resultbias2,khidist)







